name: example
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  dart_nostr:
    path: ../
  http: ^0.13.5
  isar: ^3.0.5
  logging: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
