name: dart_nostr
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bip340: ^0.0.4
  crypto: ^3.0.2
  equatable: ^2.0.5
  hex: ^0.2.0
  isar: ^3.0.5
  logging: ^1.1.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3
